### PR TITLE
Observation csv cleanup

### PR DESCRIPTION
**Pull request by strychemi**
So finished up the minimal CSV download feature, should align more closely with expected excel spreadsheet format used by the staff. 

Also did a ton of refactoring, broke things into partials so the templating isn't as insane.

You'll also notice I went back to the weird chained method calls in 2 places (lines 7-9 in _sample_table.html.erb partial and line 9 in survey_protocols.rb model file).  This is because the Observation#sample_field_names method gives me the wrong set of column titles for the sample data, so I would get like 5 columns in the table header with 10+ columns of data in the table body.

I ran the following lines in rails console and what I get don't match up.

``` Ruby
SurveyProtocol.first.sample_fields.map { |field| field["label"] }
SurveyProtocol.first.observations.first.samples.first.response_data
```

The fields don't seem to match up, bit weird maybe I'm missing something?
Everything else seems alright, though.

screen shot 2016-07-13 at 10 22 55 pm

### CODE REVIEW

**Comment by h-m-m** [comment]
Yes, there is no guarantee the way the code is written that
`SurveyProtocol.first.sample_fields.map { |field| field["label"] }` and `SurveyProtocol.first.observations.first.samples.first.response_data` will have fields that match up.

In part, this is because the sample_fields for a given SurveyProtocol may change after the first observation using that protocol was created. I've also seen some ordering inconsistencies when testing in my local development environment. There may also be some cleanup of seed data that we need to do.

I feel like this is a good point in time to ask the stakeholders / users for clarification on how they want to handle SurveyProtocol changes, specifically asking them what they want to do if they find a protocol is mostly OK, but it needs one small change. We will hopefully have a conference call with them some afternoon next week, and I can include you in on that, @strychemi, if you're interested.

**Comment by h-m-m** [comment]
Also: thank you for doing the work on refactoring this. And thanks for the screenshot in the PR, I do think those are very useful. I'll likely have a few more questions about this code, and I plan to look at it at NoVa Code & Coffee tomorrow.

**Comment by strychemi** [comment]
Gotcha, thanks for the clarification, @h-m-m !

Definitely would love to chat to get a better idea on what their needs are and how we could better address it, so I'd definitely be interested in participating. Feel free to let me know via email when there's a date/time!

I'll also probably drop by at NoVa Code & Coffee tomorrow and can give a quick rundown of the PR.

**Comment by h-m-m** [comment]
Thanks for your patience while we were on hiatus working on this project.

There's still work to be done here, but I'm going to merge in this branch. This is good work here. We can start new PRs for new issues as we find them.

**Pull request merged**
