### PR TITLE
UJS autocomplete

### LINKED ISSUE #46: Invalid AR query
I've written how I'd like the Auto-complete query to work but I'm getting the following error.

SQL Query

``` sql
SELECT  DISTINCT "taxa"."common_name" FROM "taxa" WHERE (common_name ILIKE 'Co') LIMIT 8
```

and the error

``` ruby
Taxon Load (41.5ms)  SELECT "taxa".* FROM "taxa" WHERE (SELECT)
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  subquery must return only one column
LINE 1: SELECT "taxa".* FROM "taxa" WHERE (SELECT)
```

See file `app/controllers/ujs_controller.rb`

### PR DESCRIPTION
**Pull request by danielpclark**
fixes #46

### CODE REVIEW

**Comment by bglusman** [comment]
I think this branch is in a weird state w/r to the active admin branch, I can't run it for lack of activeadmin in Gemfile, so tried a few quick fixes pulling things from other branches, but had to rebase on the activeadmin branch to get it to successfully migrate and boot..  will push up that branch I guess as it's own PR?  unless @danielpclark wants to take a look first/just update this one, don't want to force push here without his OK.

**Comment by danielpclark** [comment]
Yeah it kind of had ActiveAdmin integrated.  I'm cool with your changes.

**Comment by bglusman** [comment]
OK, cool, closing in favor of #53 shall we also close #50 since #53 includes that via rebase?  @h-m-m ?

**Comment by h-m-m** [comment]
@bglusman @danielpclark If it's easy it separate UJS and the ActiveAdmin changes, that would be nice. If separating them is something more than 30 minutes of work, I don't think it's worth it and we can merge them in together.

**Comment by danielpclark** [comment]
If you don't mind losing the history it would be easy to clone a second folder and copy it over.  Then just the changes will be there for a new PR but without any of the commit history.

**Comment by danielpclark** [comment]
Done! @h-m-m @bglusman with @bglusman improvements on the appropriate branch. #58 and #57

**Comment by danielpclark** [comment]
@bglusman I'm curious to hear about your experience trying it (the good PR) out.

**Pull request closed without merging**
