### PR TITLE
Just the ready ActiveAdmin code

### PR DESCRIPTION
**Pull request by danielpclark**
@h-m-m Here's a clean ActiveAdmin PR

### CODE REVIEW

**Comment by danielpclark** [comment]
Could use the last revision @bglusman added on the UJS channel though

**Comment by h-m-m** [comment]
Was the hstore editing in the last PR?
I like how this ActiveAdmin setup manages Properties, Sites, and Subsites. I'm fine with it for anything else not managed or modifiable any way yet anywhere else. If we start allowing more than one system to modify the same tables, we open ourselves up to a class of bugs I'd like to avoid.

**Comment by danielpclark** [comment]
Right.  No it wasn't in the last PR.  I had thought to add it in, but do you think we should hold off on it?  We can always cherry pick it later.

**Comment by danielpclark** [comment]
Alright I removed it

```
git reset --hard HEAD~1
git push --force origin clean_activerecord_migration
```

**Comment by bglusman** [comment]
@h-m-m not sure I under stand concern over editing the hstores, if they
can't edit responses in admin how will they fix/sanitize problematic data?
You want to link to using the entry and sample entry forms for editing them
instead? This may be a practical question for them to understand needs,
seems odd to not be able to admin all the data in one place.

**Comment by h-m-m** [comment]
@bglusman I was under the impression we would roll something different to allow for QA and not fold it in to ActiveAdmin. I'd like to talk about our approach to sanitizing this data and make sure everyone can understand where we're going before making changes. ActiveAdmin may be a great approach, but it was a surprise to me when I saw this.

My main concern about folding it in to ActiveAdmin is that ActiveAdmin doesn't know when edits to the hstore field violate what's defined in the protocol table.

Since that's now out of this PR, it looks good to me.

**Pull request merged**
